---
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: mon-staging
    groups:
      - securedrop_monitor_server
      - mon-staging
      - staging
      - securedrop

  - name: app-staging
    groups:
      - securedrop_application_server
      - app-staging
      - staging
      - securedrop
provisioner:
  name: ansible
  playbooks:
    side_effect: side_effect.yml
  lint:
    name: ansible-lint
  options:
    skip-tags: "grsec,local_build"
    e: "@ami-build-vars.yml"
  config_options:
    defaults:
      callback_whitelist: "profile_tasks, timer"
  inventory:
    links:
      group_vars: sd-orig/install_files/ansible-base/group_vars
      host_vars: sd-orig/install_files/ansible-base/host_vars
  env:
    ANSIBLE_ROLES_PATH: .molecule/sd-orig/install_files/ansible-base/roles
scenario:
  name: ami-builder
  test_sequence:
    - create
    - converge
    - side_effect
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
