---

- name: Configure apt-server
  hosts: aptservers
  become: yes
  tasks:
    - import_tasks: local_apt_mirror.yml
      when: lookup('env','QA_FPF_REPO') == ''

  vars:
    molecule_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}"
    dpkg_dir: /var/repos/debs
    rep_dist: trusty
    rep_component: main
    rep_arch: i386 amd64
    release_file: "/var/repos/base/dists/{{ rep_dist }}/Release"
    nginx_sites:
      default:
        - listen 80
        - root "/var/repos/base"
        - location / { autoindex on; }
      encrypted:
        - listen 443 ssl
        - server_name apt.freedom.press
        - ssl_certificate /etc/ssl/certs/apt_freedom_press.pem
        - ssl_certificate_key /etc/ssl/private/apt_freedom_press.priv
        - root "/var/repos/base"
        - location / { autoindex on; }

- name: Configure apt-server
  hosts: securedrop
  gather_facts: false
  become: yes
  tasks:
    - block:
        - name: Redirect to local QA Apt server
          set_fact:
            apt_key_bits:
              - url: "http://{{ hostvars['apt']['ansible_eth0'].ipv4.address }}/apt-test.pub"
                id: 6D65484B
            apt_test_etc_line: "{{ hostvars['apt']['ansible_eth0'].ipv4.address }}  apt.freedom.press"
          when: lookup('env','QA_FPF_REPO') == ''

        - name: Redirect to FPF QA Apt server
          set_fact:
            apt_key_bits:
              - data: "{{ lookup('file','files/apt-test-fpf.pub') }}"
            apt_test_etc_line: "{{ lookup('dig', 'apt-test.freedom.press') }}  apt.freedom.press"
          when: lookup('env','QA_FPF_REPO') != ''

        - name: Install testing apt key to keyring
          apt_key:
            id: "{{ item.id|default(omit) }}"
            url: "{{ item.url|default(omit) }}"
            data: "{{ item.data|default(omit) }}"
            state: present
          with_items: "{{ apt_key_bits }}"

        - name: Redirect apt.freedom.press to local apt server
          lineinfile:
            path: /etc/hosts
            regexp: apt.freedom.press$
            line: "{{ apt_test_etc_line }}"

        - name: Add apt-test CA to CA trusted store
          copy:
            src: cacert.pub
            dest: /usr/local/share/ca-certificates/fpf_test_ca.crt
          notify: update ca
          when: lookup('env','QA_FPF_REPO') == ''
      tags: apt

  handlers:
    - name: update ca
      command: update-ca-certificates
