---
- name: Re-run original tor role
  hosts: securedrop
  max_fail_percentage: 0
  any_errors_fatal: yes
  pre_tasks:
    - name: Fix hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item.line }}"
        regexp: "{{ item.reg }}"
      with_items: "{{ etc_hosts[ansible_hostname] }}"
      tags: hosts
  roles:
    - { role: tor-hidden-services, tags: tor }
    - { role: restrict-direct-access, tags: [ firewall ] }
  post_tasks:
    - import_tasks: reboot_and_wait.yml
  become: yes

- name: Re-run OSSEC role
  hosts: securedrop
  max_fail_percentage: 0
  any_errors_fatal: yes
  roles:
    - role: ossec
      tags: ossec
  become: yes

- import_playbook: apt.yml
  tags: apt
